### ISSUE TITLE
Local gulp not found in /src

### ISSUE THREAD

**Issue by Brett-A-T-Anderson** [mkenney/docker-npm#170]
So I'm just trying to use this to run gulp, I installed the install script and used it to grab gulp. Then I grabbed the wrapperfile but whenever I try to execute it I get 

`[22:34:57] Local gulp not found in /src
[22:34:57] Try running: npm install gulp`

Was there an install step I missed?

**Comment by mkenney** [comment]
Hi @Brett-A-T-Anderson,

Generally, for gulp, you need it installed locally in your project as well. If this is an otherwise working project I think you need to run `npm install` or `yarn install` first.

For example, here is my package.json: https://github.com/mkenney/docker-npm/blob/master/test/resources/package.json

And here is my Gulpfile: https://github.com/mkenney/docker-npm/blob/master/test/resources/gulpfile.js

To run that test I can execute `yarn install && gulp` from that folder. Does that help?
